//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicPot.Backend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagicPot.Backend.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is not a Jetton Master address..
        /// </summary>
        public static string AddressIsNotAJetton {
            get {
                return ResourceManager.GetString("AddressIsNotAJetton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value is 99:59.
        /// </summary>
        public static string MaxValueIs99h59m {
            get {
                return ResourceManager.GetString("MaxValueIs99h59m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of all shares must be equal to 100..
        /// </summary>
        public static string SumOfSharesMustBe100 {
            get {
                return ResourceManager.GetString("SumOfSharesMustBe100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating your jetton wallet... Please retry in 5-10 seconds..
        /// </summary>
        public static string ValidatingUserJettonWallet {
            get {
                return ResourceManager.GetString("ValidatingUserJettonWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last players percent and number must be both set or both empty..
        /// </summary>
        public static string ValuesInconsistentLastTransactions {
            get {
                return ResourceManager.GetString("ValuesInconsistentLastTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random players percent and number must be both set or both empty..
        /// </summary>
        public static string ValuesInconsistentRandomTransactions {
            get {
                return ResourceManager.GetString("ValuesInconsistentRandomTransactions", resourceCulture);
            }
        }
    }
}
